import Link from 'next/link';
import {requireCapabilitiesPage} from '@/lib/admin/access';
import {catalogFilters,type CatalogFilters} from '@/lib/admin/catalog.service';
import {AdminProductTable} from '@/components/admin/AdminProductTable';
import {AdminPagination} from '@/components/admin/AdminPagination';
export default async function AdminProductsPage({searchParams}:{searchParams:Promise<CatalogFilters>}) {
  const {supabase}=await requireCapabilitiesPage('/admin/products',['products.read']);
  const filters=catalogFilters(await searchParams);const pageSize=30;
  const [result,permissions,brands,categories]=await Promise.all([
    supabase.rpc('admin_catalog_products',{...filters.rpc,page_offset:(filters.page-1)*pageSize,page_limit:pageSize}),
    supabase.rpc('my_capabilities'),supabase.from('brands').select('id,name').order('name').limit(500),supabase.from('categories').select('id,name').order('name').limit(500),
  ]);
  if(result.error)throw new Error('Products are temporarily unavailable.');
  const allowed=new Set(permissions.data?.map((v)=>v.capability));
  const rows=(result.data??[]).map((product)=>({...product,image_url:product.image_path?(product.image_path.startsWith('/')?product.image_path:supabase.storage.from('product-images').getPublicUrl(product.image_path).data.publicUrl):null}));
  return <section className="px-4 pb-20 pt-8 sm:px-7 lg:px-10"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#087456]">Catalog workspace</p><h1 className="mt-2 text-4xl font-black tracking-[-0.05em]">Products</h1><p className="mt-2 text-sm text-[#61766b]">Canonical records, variants and actual live inventory. Drafts are invisible to shoppers.</p></div><div className="flex items-end gap-2">{allowed.has('products.write')&&<Link href="/admin/products/new" className="rounded-lg bg-[#0d211a] px-4 py-2 text-xs font-bold text-white">New draft</Link>}{allowed.has('products.import')&&<Link href="/admin/imports" className="rounded-lg border border-[#c8d9cb] bg-white px-4 py-2 text-xs font-bold">Bulk import</Link>}</div></div><form method="get" className="mt-6 flex flex-wrap gap-3 rounded-2xl border border-[#dce6dc] bg-white p-4"><input name="q" defaultValue={filters.url.q} aria-label="Search catalog" placeholder="Name, SKU or style code" className="rounded-lg border border-[#dce6dc] p-2 text-sm"/>{[{name:'brand',label:'All brands',value:filters.url.brand,options:brands.data?.map((v)=>({value:v.id,label:v.name}))??[]},{name:'category',label:'All categories',value:filters.url.category,options:categories.data?.map((v)=>({value:v.id,label:v.name}))??[]},{name:'status',label:'All states',value:filters.url.status,options:['active','draft','archived'].map((v)=>({value:v,label:v}))},{name:'featured',label:'Featured (all)',value:filters.url.featured,options:[{value:'true',label:'Featured'},{value:'false',label:'Not featured'}]},{name:'wanted',label:'Most Wanted (all)',value:filters.url.wanted,options:[{value:'true',label:'Most Wanted'},{value:'false',label:'Not Most Wanted'}]}].map((field)=><select key={field.name} name={field.name} defaultValue={field.value} aria-label={field.name} className="rounded-lg border border-[#dce6dc] bg-white p-2 text-sm"><option value="">{field.label}</option>{field.options.map((v)=><option key={v.value} value={v.value}>{v.label}</option>)}</select>)}<select name="sort" defaultValue={filters.url.sort} aria-label="Sort products" className="rounded-lg border border-[#dce6dc] bg-white p-2 text-sm"><option value="updated">Recently updated</option><option value="name">Name</option><option value="price">Lowest live price</option></select><button className="rounded-lg bg-[#0d211a] px-4 py-2 text-xs font-bold text-white">Filter</button></form><div className="mt-5"><AdminProductTable rows={rows} manage={allowed.has('products.write')} canExport={allowed.has('products.export')} exportQuery={new URLSearchParams(filters.url).toString()}/><div className="rounded-b-2xl border border-t-0 border-[#dce6dc] bg-white"><AdminPagination basePath="/admin/products" page={filters.page} count={result.data?.[0]?.total_count??0} pageSize={pageSize} filters={filters.url}/></div></div></section>;
}
